import type { Vehicle } from "@/lib/types";
import {
  getRetailStock,
  getTradeStock,
  isRetailVehicle,
  isTradeVehicle,
} from "@/lib/vehicle-stock";

export const vehicles: Vehicle[] = [
  {
    id: "v001",
    slug: "2018-ford-focus-st-line",
    make: "Ford",
    model: "Focus",
    variant: "1.5 EcoBoost ST-Line 5dr",
    year: 2018,
    mileage: 54200,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    doors: 5,
    seats: 5,
    colour: "Magnetic Grey",
    registration: "MA18 FCS",
    engineCC: 1499,
    price: 8995,
    description:
      "A well-presented Focus ST-Line in Magnetic Grey. Drives solidly with good power delivery. Service history present. A few minor stone chips on the bonnet — all declared.",
    images: [
      "/images/vehicles/car-06.jpg?v=2",
      "/images/vehicles/car-02.jpg?v=2",
      "/images/vehicles/car-04.jpg?v=2",
      "/images/vehicles/car-05.jpg?v=2",
    ],
    imageAlts: [
      "2018 Ford Focus front three-quarter view",
      "2018 Ford Focus rear three-quarter view",
      "2018 Ford Focus driver side view",
      "2018 Ford Focus interior view",
    ],
    hasVideo: true,
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    serviceHistoryPresent: true,
    serviceHistoryStatus: "full",
    serviceRecords: [
      { date: "2024-02-10", mileage: 52800, type: "Interim Service", location: "Independent, Leigh" },
      { date: "2022-06-15", mileage: 46800, type: "Interim Service", location: "Independent, Leigh" },
      { date: "2021-05-20", mileage: 36400, type: "Full Service", location: "Kwik Fit, Salford" },
      { date: "2020-04-08", mileage: 24100, type: "Full Service", location: "Ford Main Dealer, Manchester" },
      { date: "2019-04-12", mileage: 12300, type: "Interim Service", location: "Ford Main Dealer, Manchester" },
    ],
    v5cStatus: "present-in-name",
    keys: { count: 1, sparePresent: false },
    documentImages: [
      {
        id: "v001-d1",
        type: "service-book",
        label: "Service book",
        imageUrl: "/images/vehicles/car-04.jpg?v=2",
        alt: "Service book",
      },
      {
        id: "v001-d2",
        type: "mot-certificate",
        label: "MOT certificate",
        imageUrl: "/images/vehicles/car-05.jpg?v=2",
        alt: "MOT certificate",
      },
      {
        id: "v001-d3",
        type: "invoice",
        label: "Invoice",
        imageUrl: "/images/vehicles/car-02.jpg?v=2",
        alt: "Service invoice",
      },
      {
        id: "v001-d4",
        type: "keys",
        label: "Keys",
        imageUrl: "/images/vehicles/car-06.jpg?v=2",
        alt: "Keys",
      },
    ],
    documents: [
      { name: "V5C Logbook", present: true },
      { name: "MOT Certificate", present: true },
      { name: "Service Book", present: true },
      { name: "Spare Key", present: false },
    ],
    conditionItems: [
      {
        id: "c1",
        title: "Stone chips on bonnet leading edge",
        severity: "advisory",
        photo: "/images/vehicles/car-06.jpg?v=2",
        photoAlt: "Stone chips on bonnet leading edge under 3mm",
        qualifiers: ["under 3mm", "6–8 chips"],
      },
      {
        id: "c2",
        title: "Light surface scratch on rear nearside door",
        severity: "advisory",
        photo: "/images/vehicles/car-02.jpg?v=2",
        photoAlt: "Light surface scratch on rear nearside door approximately 4cm",
        qualifiers: ["~4cm", "paint intact"],
        detail: "Does not break the paint",
      },
      {
        id: "c3",
        title: "Wear to driver seat bolster",
        severity: "advisory",
        photo: "/images/vehicles/car-04.jpg?v=2",
        photoAlt: "Driver seat bolster wear consistent with age and mileage",
        qualifiers: ["cosmetic", "no tears"],
        detail: "Normal wear consistent with age and mileage",
      },
      {
        id: "c4",
        title: "Nearside front tyre low on tread",
        severity: "minor",
        photo: "/images/vehicles/car-05.jpg?v=2",
        photoAlt: "Nearside front tyre with 3.0mm tread",
        qualifiers: ["3.0mm", "legal", "replace soon"],
      },
    ],
    motHistory: [
      {
        date: "2024-03-14",
        result: "pass",
        mileage: 51200,
        advisories: ["Tyre worn close to legal limit (4.1.E.1) — nearside front"],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
      {
        date: "2023-03-09",
        result: "pass",
        mileage: 44100,
        advisories: ["Wiper blade smearing (8.2.4) — driver side"],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
      {
        date: "2022-03-22",
        result: "fail",
        mileage: 36900,
        advisories: [],
        failures: ["Nearside front brake disc worn below minimum thickness (1.1.11 (a) (i))"],
        testCenter: "Kwik Fit, Salford",
      },
      {
        date: "2022-04-04",
        result: "pass",
        mileage: 36910,
        advisories: [],
        failures: [],
        testCenter: "Kwik Fit, Salford",
        rectifiedNote: "Rectified same day",
      },
    ],
    motExpiry: "2025-03-14",
    runningCosts: { mpgCombined: 44, mpgUrban: 37, mpgExtra: 50, insuranceGroup: 18, insuranceGroupSuffix: "E", roadTaxAnnual: 195, co2gkm: 148 },
    formerKeepers: 2,
    lat: 53.4968, lng: -2.5149,
    isTrade: false,
    listedAt: "2024-11-01T10:00:00Z",
  },
  {
    id: "v002",
    slug: "2016-volkswagen-golf-gt",
    make: "Volkswagen",
    model: "Golf",
    variant: "2.0 TDI GT 5dr",
    year: 2016,
    mileage: 78400,
    fuelType: "Diesel",
    transmission: "Manual",
    bodyType: "Hatchback",
    doors: 5,
    seats: 5,
    colour: "Urano Grey",
    engineCC: 1968,
    price: 6995,
    description:
      "Solid Golf GT TDI — great motorway cruiser with good economy. Full service history to 68k then a gap. Two minor rust bubbles on nearside sill declared.",
    images: ["/images/vehicles/car-02.jpg?v=2"],
    hasVideo: false,
    serviceHistoryPresent: true,
    serviceHistoryStatus: "full",
    serviceRecords: [
      { date: "2017-05-10", mileage: 18200, type: "Full Service", location: "VW Main Dealer, Bolton" },
      { date: "2018-05-14", mileage: 30100, type: "Full Service", location: "VW Main Dealer, Bolton" },
      { date: "2019-06-20", mileage: 43400, type: "Full Service", location: "VW Main Dealer, Bolton" },
      { date: "2020-07-08", mileage: 55600, type: "Interim Service", location: "Halfords Autocentre" },
      { date: "2021-08-02", mileage: 68000, type: "Full Service", location: "Halfords Autocentre" },
    ],
    documents: [
      { name: "V5C Logbook", present: true },
      { name: "MOT Certificate", present: true },
      { name: "Service Book", present: true },
      { name: "Spare Key", present: true },
    ],
    conditionItems: [
      {
      id: "c1",
            title: "rust bubbles on nearside sill",
            severity: "minor",
            photo: "/images/vehicles/car-02.jpg?v=2",
            photoAlt: "Rust bubbles on nearside sill — approx5mm",
            qualifiers: ["approx5mm"],
            detail: "approx 5mm each, have been treated but visible",
          },
      {
      id: "c2",
            title: "Scuff mark on offside rear bumper, approx 8cm",
            severity: "advisory",
            photo: "/images/vehicles/car-02.jpg?v=2",
            photoAlt: "Scuff mark on offside rear bumper, approx 8cm — 8cm",
            qualifiers: ["8cm"],
            detail: "colour transfer from minor car park contact",
          },
      {
      id: "c3",
            title: "Centre console lid has a crack across the hinge",
            severity: "advisory",
            photo: "/images/vehicles/car-02.jpg?v=2",
            photoAlt: "Centre console lid has a crack across the hinge — cosmetic, functional",
            qualifiers: ["cosmetic", "functional"],
            detail: "functional but cosmetically imperfect",
          },
    ],
    motHistory: [
      {
        date: "2024-06-18",
        result: "pass",
        mileage: 76100,
        advisories: ["Nearside sill corroded (7.1.1 (a)) — monitor"],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
      {
        date: "2023-06-12",
        result: "pass",
        mileage: 70200,
        advisories: ["Windscreen wiper blade deteriorated (8.2.4)"],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
      {
        date: "2022-06-08",
        result: "pass",
        mileage: 64800,
        advisories: ["Slight oil leak · brake discs lightly scored"],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
      {
        date: "2021-05-20",
        result: "pass",
        mileage: 58400,
        advisories: [],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
      {
        date: "2020-05-14",
        result: "pass",
        mileage: 51200,
        advisories: ["Nearside front tyre worn close to legal limit"],
        failures: [],
        testCenter: "Halfords Autocentre, Bolton",
      },
      {
        date: "2019-05-09",
        result: "fail",
        mileage: 44100,
        advisories: [],
        failures: ["Offside headlamp aim too high (1.2.1 (a))"],
        testCenter: "Halfords Autocentre, Bolton",
      },
      {
        date: "2019-05-10",
        result: "pass",
        mileage: 44100,
        advisories: [],
        failures: [],
        testCenter: "Halfords Autocentre, Bolton",
        rectifiedNote: "Rectified same day",
      },
      {
        date: "2018-05-22",
        result: "pass",
        mileage: 36800,
        advisories: ["Rear brake pad(s) wearing thin (1.1.13 (a) (ii))"],
        failures: [],
        testCenter: "VW Main Dealer, Bolton",
      },
      {
        date: "2017-05-18",
        result: "pass",
        mileage: 29100,
        advisories: [],
        failures: [],
        testCenter: "VW Main Dealer, Bolton",
      },
      {
        date: "2016-05-12",
        result: "pass",
        mileage: 21400,
        advisories: [],
        failures: [],
        testCenter: "VW Main Dealer, Bolton",
      },
    ],
    formerKeepers: 3,
    v5cStatus: "present-in-name",
    keys: { count: 2, sparePresent: true },
    documentImages: [
      {
        id: "v002-d1",
        type: "service-book",
        label: "Service book",
        imageUrl: "/images/vehicles/car-02.jpg?v=2",
        alt: "Service book",
      },
      {
        id: "v002-d2",
        type: "mot-certificate",
        label: "MOT certificate",
        imageUrl: "/images/vehicles/car-02.jpg?v=2",
        alt: "MOT certificate",
      },
      {
        id: "v002-d3",
        type: "invoice",
        label: "Invoice",
        imageUrl: "/images/vehicles/car-02.jpg?v=2",
        alt: "Service invoice",
      },
      {
        id: "v002-d4",
        type: "keys",
        label: "Keys",
        imageUrl: "/images/vehicles/car-02.jpg?v=2",
        alt: "Keys",
      },
    ],
    motExpiry: "2025-06-18",
    runningCosts: { mpgCombined: 61, mpgUrban: 51, mpgExtra: 67, insuranceGroup: 22, roadTaxAnnual: 165, co2gkm: 122 },
    lat: 53.4968, lng: -2.5149,
    isTrade: false,
    listedAt: "2024-10-15T09:30:00Z",
  },
  {
    id: "v003",
    slug: "2020-vauxhall-astra-sri",
    make: "Vauxhall",
    model: "Astra",
    variant: "1.2 Turbo SRi 5dr",
    year: 2020,
    mileage: 31800,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    doors: 5,
    seats: 5,
    colour: "Sovereign Silver",
    engineCC: 1199,
    price: 11495,
    description:
      "Low mileage Astra SRi in very good condition overall. Virtually unmarked interior. Two advisory items declared — both cosmetic.",
    images: ["/images/vehicles/car-09.jpg?v=2"],
    hasVideo: true,
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    serviceHistoryPresent: true,
    serviceHistoryStatus: "part",
    serviceRecords: [
      { date: "2021-04-20", mileage: 10200, type: "Full Service", location: "Vauxhall Main Dealer, Wigan" },
      { date: "2022-05-11", mileage: 20800, type: "Full Service", location: "Vauxhall Main Dealer, Wigan" },
      { date: "2023-06-08", mileage: 30100, type: "Interim Service", location: "BBC Autos, Leigh" },
    ],
    v5cStatus: "present-not-in-name",
    formerKeepers: 4,
    keys: { count: 2, sparePresent: true },
    maintenanceEvidence: [
      { type: "cambelt", detail: "Changed Aug 2023 · invoice held" },
    ],
    documentImages: [
      {
        id: "v003-d1",
        type: "service-book",
        label: "Service book",
        imageUrl: "/images/vehicles/car-09.jpg?v=2",
        alt: "Service book",
      },
      {
        id: "v003-d2",
        type: "cambelt",
        label: "Cambelt invoice",
        imageUrl: "/images/vehicles/car-09.jpg?v=2",
        alt: "Cambelt invoice",
      },
      {
        id: "v003-d3",
        type: "handbook",
        label: "Handbook",
        imageUrl: "/images/vehicles/car-09.jpg?v=2",
        alt: "Handbook",
      },
    ],
    documents: [
      { name: "V5C Logbook", present: true },
      { name: "MOT Certificate", present: true },
      { name: "Service Book", present: true },
      { name: "Spare Key", present: true },
    ],
    conditionItems: [
      {
      id: "c1",
            title: "stone chip on roof front edge",
            severity: "advisory",
            photo: "/images/vehicles/car-09.jpg?v=2",
            photoAlt: "Stone chip on roof front edge — 1mm, no rust",
            qualifiers: ["1mm", "no rust"],
            detail: "1mm, no rust",
          },
      {
      id: "c2",
            title: "swirl marks on bonnet visible in direct sunlight",
            severity: "advisory",
            photo: "/images/vehicles/car-09.jpg?v=2",
            photoAlt: "Swirl marks on bonnet visible in direct sunlight",
            detail: "common with silver paint",
          },
    ],
    motHistory: [
      {
        date: "2024-05-02",
        result: "pass",
        mileage: 30100,
        advisories: [],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
      {
        date: "2023-05-09",
        result: "pass",
        mileage: 21400,
        advisories: [],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
    ],
    motExpiry: "2025-05-02",
    runningCosts: { mpgCombined: 47, mpgUrban: 40, mpgExtra: 52, insuranceGroup: 14, roadTaxAnnual: 180, co2gkm: 135 },
    lat: 53.4968, lng: -2.5149,
    isTrade: false,
    listedAt: "2024-11-10T11:00:00Z",
  },
  {
    id: "v004",
    slug: "2015-honda-jazz-se",
    make: "Honda",
    model: "Jazz",
    variant: "1.3 i-VTEC SE 5dr",
    year: 2015,
    mileage: 62100,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    doors: 5,
    seats: 5,
    colour: "Crystal Black",
    engineCC: 1339,
    price: 5995,
    description:
      "Reliable Jazz SE with very practical Magic Seats. Well maintained with consistent service history. A few age-related marks — all declared.",
    images: ["/images/vehicles/car-04.jpg?v=2"],
    hasVideo: false,
    serviceHistoryPresent: true,
    serviceHistoryStatus: "full",
    serviceRecords: [
      { date: "2016-06-14", mileage: 11200, type: "Full Service", location: "Honda Main Dealer, Warrington" },
      { date: "2017-07-03", mileage: 22400, type: "Full Service", location: "Honda Main Dealer, Warrington" },
      { date: "2018-07-22", mileage: 33600, type: "Full Service", location: "Honda Main Dealer, Warrington" },
      { date: "2019-08-15", mileage: 43200, type: "Interim Service", location: "Independent, Leigh" },
      { date: "2021-09-10", mileage: 56800, type: "Full Service", location: "Independent, Leigh" },
    ],
    documents: [
      { name: "V5C Logbook", present: true },
      { name: "MOT Certificate", present: true },
      { name: "Service Book", present: true },
      { name: "Spare Key", present: false },
    ],
    conditionItems: [
      {
      id: "c1",
            title: "Chips and light scratches on rear bumper",
            severity: "advisory",
            photo: "/images/vehicles/car-04.jpg?v=2",
            photoAlt: "Chips and light scratches on rear bumper",
            detail: "typical for age",
          },
      {
      id: "c2",
            title: "Rear seat squab has a small (2cm) tear on the passenger side",
            severity: "advisory",
            photo: "/images/vehicles/car-04.jpg?v=2",
            photoAlt: "Rear seat squab has a small (2cm) tear on the passenger side — 2cm",
            qualifiers: ["2cm"],
            detail: "not visible when folded",
          },
      {
      id: "c3",
            title: "dent on offside rear quarter",
            severity: "minor",
            photo: "/images/vehicles/car-04.jpg?v=2",
            photoAlt: "Dent on offside rear quarter — 20mm",
            qualifiers: ["20mm"],
            detail: "20mm, no paint damage",
          },
    ],
    motHistory: [
      {
        date: "2024-08-20",
        result: "pass",
        mileage: 60400,
        advisories: ["Rear brake pads approaching minimum (1.2.1 (f) (i))"],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
      {
        date: "2023-08-14",
        result: "pass",
        mileage: 56100,
        advisories: [],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
    ],
    motExpiry: "2025-08-20",
    runningCosts: { mpgCombined: 54, mpgUrban: 46, mpgExtra: 59, insuranceGroup: 9, roadTaxAnnual: 155, co2gkm: 119 },
    lat: 53.4968, lng: -2.5149,
    isTrade: false,
    listedAt: "2024-09-20T14:00:00Z",
  },
  {
    id: "v005",
    slug: "2019-toyota-yaris-icon-tech",
    make: "Toyota",
    model: "Yaris",
    variant: "1.5 VVT-i Icon Tech 5dr",
    year: 2019,
    mileage: 28400,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    doors: 5,
    seats: 5,
    colour: "Chilli Red",
    engineCC: 1496,
    price: 10995,
    description:
      "Excellent low mileage Yaris in Chilli Red. Known for reliability. One advisory item on the last MOT — noted here for transparency.",
    images: ["/images/vehicles/car-05.jpg?v=2"],
    hasVideo: true,
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    serviceHistoryPresent: true,
    serviceHistoryStatus: "part",
    serviceRecords: [
      { date: "2020-05-08", mileage: 10100, type: "Full Service", location: "Toyota Main Dealer, Manchester" },
      { date: "2021-05-14", mileage: 17800, type: "Full Service", location: "Toyota Main Dealer, Manchester" },
      { date: "2022-06-01", mileage: 23200, type: "Interim Service", location: "Toyota Main Dealer, Manchester" },
    ],
    documents: [
      { name: "V5C Logbook", present: true },
      { name: "MOT Certificate", present: true },
      { name: "Service Book", present: true },
      { name: "Spare Key", present: true },
    ],
    conditionItems: [
      {
      id: "c1",
            title: "chip on offside front door lower edge",
            severity: "advisory",
            photo: "/images/vehicles/car-05.jpg?v=2",
            photoAlt: "Chip on offside front door lower edge — 2mm, no rust",
            qualifiers: ["2mm", "no rust"],
            detail: "2mm, no rust present",
          },
    ],
    motHistory: [
      {
        date: "2024-04-22",
        result: "pass",
        mileage: 27100,
        advisories: ["Bonnet release mechanism slightly stiff (3.4.1 (a)) — lubricated at test"],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
      {
        date: "2023-04-18",
        result: "pass",
        mileage: 22400,
        advisories: [],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
    ],
    motExpiry: "2025-04-22",
    runningCosts: { mpgCombined: 51, mpgUrban: 44, mpgExtra: 56, insuranceGroup: 10, roadTaxAnnual: 170, co2gkm: 126 },
    lat: 53.4968, lng: -2.5149,
    isTrade: false,
    listedAt: "2024-10-28T09:00:00Z",
  },
  {
    id: "v006",
    slug: "2014-bmw-3-series-320d",
    make: "BMW",
    model: "3 Series",
    variant: "320d SE Saloon",
    year: 2014,
    mileage: 102300,
    fuelType: "Diesel",
    transmission: "Manual",
    bodyType: "Saloon",
    doors: 4,
    seats: 5,
    colour: "Space Grey",
    engineCC: 1995,
    price: 7995,
    description:
      "High mileage but well maintained 320d — these engines are known to last 200k+ with care. Full service history to 98k. Multiple condition items declared.",
    images: ["/images/vehicles/car-06.jpg?v=2"],
    hasVideo: true,
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    serviceHistoryPresent: true,
    serviceHistoryStatus: "full",
    serviceRecords: [
      { date: "2015-09-10", mileage: 18400, type: "Full Service", location: "BMW Main Dealer, Manchester" },
      { date: "2016-09-12", mileage: 34600, type: "Full Service", location: "BMW Main Dealer, Manchester" },
      { date: "2017-09-18", mileage: 50200, type: "Full Service", location: "BMW Main Dealer, Manchester" },
      { date: "2018-10-04", mileage: 65800, type: "Full Service", location: "Independent BMW Specialist" },
      { date: "2019-10-14", mileage: 79400, type: "Full Service", location: "Independent BMW Specialist" },
      { date: "2020-11-02", mileage: 90100, type: "Full Service", location: "Independent BMW Specialist" },
      { date: "2022-01-24", mileage: 98200, type: "Interim Service", location: "Independent BMW Specialist" },
    ],
    documents: [
      { name: "V5C Logbook", present: true },
      { name: "MOT Certificate", present: true },
      { name: "Service Book", present: true },
      { name: "Spare Key", present: true },
    ],
    conditionItems: [
      {
      id: "c1",
            title: "Scratch on nearside front wing",
            severity: "minor",
            photo: "/images/vehicles/car-06.jpg?v=2",
            photoAlt: "Scratch on nearside front wing — 15cm",
            qualifiers: ["15cm"],
            detail: "15cm, faded paint visible",
          },
      {
      id: "c2",
            title: "surface corrosion on both sills",
            severity: "minor",
            photo: "/images/vehicles/car-06.jpg?v=2",
            photoAlt: "Surface corrosion on both sills — cosmetic",
            qualifiers: ["cosmetic"],
            detail: "cosmetic at present, not structural",
          },
      {
      id: "c3",
            title: "Driver armrest has a 3cm split in the leather",
            severity: "advisory",
            photo: "/images/vehicles/car-06.jpg?v=2",
            photoAlt: "Driver armrest has a 3cm split in the leather — 3cm",
            qualifiers: ["3cm"],
            detail: "common on this model at this age",
          },
      {
      id: "c4",
            title: "iDrive controller knob has wear marks",
            severity: "advisory",
            photo: "/images/vehicles/car-06.jpg?v=2",
            photoAlt: "IDrive controller knob has wear marks — functional",
            qualifiers: ["functional"],
            detail: "functional",
          },
      {
      id: "c5",
            title: "tyres at 3mm",
            severity: "minor",
            photo: "/images/vehicles/car-06.jpg?v=2",
            photoAlt: "Tyres at 3mm — 3mm, legal",
            qualifiers: ["3mm", "legal", "replace soon"],
            detail: "legal, recommend replacement soon",
          },
      {
      id: "c6",
            title: "oil seep from rocker cover gasket",
            severity: "advisory",
            photo: "/images/vehicles/car-06.jpg?v=2",
            photoAlt: "Oil seep from rocker cover gasket — monitor",
            qualifiers: ["monitor"],
            detail: "drip-free at present, monitor",
          },
    ],
    motHistory: [
      {
        date: "2024-07-10",
        result: "pass",
        mileage: 99800,
        advisories: ["Sill corrosion nearside — monitor (7.1.1 (a))", "Rear tyre worn (4.1.E.1)"],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
      {
        date: "2023-07-06",
        result: "fail",
        mileage: 94200,
        advisories: [],
        failures: ["Offside headlamp aim too low (4.3.1 (b) (i))"],
        testCenter: "BBC Autos, Leigh",
      },
      {
        date: "2023-07-06",
        result: "pass",
        mileage: 94200,
        advisories: [],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
    ],
    motExpiry: "2025-07-10",
    runningCosts: { mpgCombined: 57, mpgUrban: 47, mpgExtra: 64, insuranceGroup: 28, roadTaxAnnual: 165, co2gkm: 129 },
    lat: 53.4968, lng: -2.5149,
    isTrade: false,
    listedAt: "2024-09-05T08:30:00Z",
  },
  {
    id: "v007",
    slug: "2021-kia-picanto-2",
    make: "Kia",
    model: "Picanto",
    variant: "1.0 2 5dr",
    year: 2021,
    mileage: 18600,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    doors: 5,
    seats: 5,
    colour: "Infra Red",
    engineCC: 998,
    price: 9495,
    description:
      "Practically new low mileage Picanto. The ideal first or city car. Virtually unmarked — only one advisory item noted.",
    images: ["/images/vehicles/car-07.jpg?v=2"],
    hasVideo: false,
    serviceHistoryPresent: true,
    serviceHistoryStatus: "full",
    serviceRecords: [
      { date: "2022-06-14", mileage: 8200, type: "Full Service", location: "Kia Main Dealer, Bolton" },
    ],
    documents: [
      { name: "V5C Logbook", present: true },
      { name: "MOT Certificate", present: true },
      { name: "Service Book", present: true },
      { name: "Spare Key", present: true },
    ],
    conditionItems: [
      {
      id: "c1",
            title: "Very faint mark on front bumper centre",
            severity: "advisory",
            photo: "/images/vehicles/car-07.jpg?v=2",
            photoAlt: "Very faint mark on front bumper centre",
            detail: "barely visible, no depth",
          },
    ],
    motHistory: [
      {
        date: "2024-06-10",
        result: "pass",
        mileage: 17800,
        advisories: [],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
    ],
    motExpiry: "2025-06-10",
    runningCosts: { mpgCombined: 56, mpgUrban: 48, mpgExtra: 61, insuranceGroup: 6, roadTaxAnnual: 155, co2gkm: 114 },
    lat: 53.4968, lng: -2.5149,
    isTrade: false,
    listedAt: "2024-11-05T12:00:00Z",
  },
  {
    id: "v008",
    slug: "2017-ford-transit-custom",
    make: "Ford",
    model: "Transit Custom",
    variant: "2.0 TDCi 290 L1 H1 Limited",
    year: 2017,
    mileage: 88700,
    fuelType: "Diesel",
    transmission: "Manual",
    bodyType: "Van",
    doors: 3,
    seats: 3,
    colour: "Frozen White",
    engineCC: 1995,
    price: 10995,
    description:
      "Well specified Transit Custom Limited in Frozen White. Multiple condition items declared openly — primarily cosmetic with one mechanical item.",
    images: ["/images/vehicles/car-08.jpg?v=2"],
    hasVideo: true,
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    serviceHistoryPresent: true,
    serviceHistoryStatus: "present-unverified",
    serviceRecords: [
      { date: "2018-07-20", mileage: 22400, type: "Full Service", location: "Ford Main Dealer, Manchester" },
      { date: "2019-07-18", mileage: 44800, type: "Full Service", location: "Ford Main Dealer, Manchester" },
      { date: "2020-08-12", mileage: 62100, type: "Interim Service", location: "Kwik Fit" },
      { date: "2021-09-03", mileage: 76400, type: "Full Service", location: "Independent" },
    ],
    documents: [
      { name: "V5C Logbook", present: true },
      { name: "MOT Certificate", present: true },
      { name: "Service Book", present: false },
      { name: "Spare Key", present: false },
    ],
    conditionItems: [
      {
      id: "c1",
            title: "Multiple scratches and dents on rear doors consistent with commercial…",
            severity: "minor",
            photo: "/images/vehicles/car-08.jpg?v=2",
            photoAlt: "Multiple scratches and dents on rear doors consistent with commercial… — cosmetic",
            qualifiers: ["cosmetic"],
            detail: "all cosmetic",
          },
      {
      id: "c2",
            title: "Offside front wing has a 30mm dent",
            severity: "minor",
            photo: "/images/vehicles/car-08.jpg?v=2",
            photoAlt: "Offside front wing has a 30mm dent — 30mm, paint intact",
            qualifiers: ["30mm", "paint intact"],
            detail: "shallow, paint intact",
          },
      {
      id: "c3",
            title: "Cab carpet worn through",
            severity: "advisory",
            photo: "/images/vehicles/car-08.jpg?v=2",
            photoAlt: "Cab carpet worn through",
            detail: "typical work van use",
          },
      {
      id: "c4",
            title: "EGR valve has been cleaned but may require replacement within 12–18 m…",
            severity: "minor",
            photo: "/images/vehicles/car-08.jpg?v=2",
            photoAlt: "EGR valve has been cleaned but may require replacement within 12–18 m…",
          },
    ],
    motHistory: [
      {
        date: "2024-09-04",
        result: "pass",
        mileage: 86200,
        advisories: ["Windscreen chip in driver's critical zone (8.1.2 (a) (ii)) — repaired prior to test"],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
      {
        date: "2023-09-11",
        result: "fail",
        mileage: 79400,
        advisories: [],
        failures: ["Offside front brake disc worn (1.1.11 (a) (i))", "Nearside wiper blade not clearing (8.2.4)"],
        testCenter: "BBC Autos, Leigh",
      },
      {
        date: "2023-09-20",
        result: "pass",
        mileage: 79410,
        advisories: [],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
    ],
    motExpiry: "2025-09-04",
    runningCosts: { mpgCombined: 34, mpgUrban: 28, mpgExtra: 38, insuranceGroup: 36, roadTaxAnnual: 290, co2gkm: 218 },
    lat: 53.4968, lng: -2.5149,
    isTrade: false,
    listedAt: "2024-10-01T10:30:00Z",
  },
  {
    id: "v009",
    slug: "2017-nissan-qashqai-acenta",
    make: "Nissan",
    model: "Qashqai",
    variant: "1.2 DiG-T Acenta 5dr",
    year: 2017,
    mileage: 49800,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "SUV",
    doors: 5,
    seats: 5,
    colour: "Blade Silver",
    engineCC: 1197,
    price: 8495,
    description:
      "Popular Qashqai Acenta in very presentable condition. Low faults — just one advisory chip on the bonnet. Good service history.",
    images: ["/images/vehicles/car-09.jpg?v=2"],
    hasVideo: false,
    serviceHistoryPresent: true,
    serviceHistoryStatus: "full",
    serviceRecords: [
      { date: "2018-06-22", mileage: 12800, type: "Full Service", location: "Nissan Main Dealer, Wigan" },
      { date: "2019-06-14", mileage: 24200, type: "Full Service", location: "Nissan Main Dealer, Wigan" },
      { date: "2020-07-18", mileage: 34800, type: "Interim Service", location: "Halfords Autocentre" },
      { date: "2021-08-09", mileage: 43600, type: "Full Service", location: "Independent" },
    ],
    documents: [
      { name: "V5C Logbook", present: true },
      { name: "MOT Certificate", present: true },
      { name: "Service Book", present: true },
      { name: "Spare Key", present: false },
    ],
    conditionItems: [
      {
      id: "c1",
            title: "Stone chips on bonnet leading edge",
            severity: "advisory",
            photo: "/images/vehicles/car-09.jpg?v=2",
            photoAlt: "Stone chips on bonnet leading edge — 2mm, 3mm",
            qualifiers: ["2mm", "3mm", "no rust"],
            detail: "2mm and 3mm, no rust",
          },
    ],
    motHistory: [
      {
        date: "2024-06-28",
        result: "pass",
        mileage: 47200,
        advisories: [],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
      {
        date: "2023-06-30",
        result: "pass",
        mileage: 43100,
        advisories: ["Nearside rear wiper blade smearing (8.2.4)"],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
    ],
    motExpiry: "2025-06-28",
    runningCosts: { mpgCombined: 43, mpgUrban: 36, mpgExtra: 48, insuranceGroup: 15, roadTaxAnnual: 180, co2gkm: 149 },
    lat: 53.4968, lng: -2.5149,
    isTrade: false,
    listedAt: "2024-10-20T11:00:00Z",
  },
  {
    id: "v010",
    slug: "2022-hyundai-i20-se-connect",
    make: "Hyundai",
    model: "i20",
    variant: "1.0 T-GDi SE Connect 5dr",
    year: 2022,
    mileage: 14200,
    fuelType: "Mild Hybrid",
    transmission: "Manual",
    bodyType: "Hatchback",
    doors: 5,
    seats: 5,
    colour: "Atlas White",
    engineCC: 998,
    price: 13495,
    description:
      "Nearly new i20 in Atlas White — virtually unmarked with low mileage. Mild hybrid tech for better economy. Full manufacturer history.",
    images: ["/images/vehicles/car-10.jpg?v=2"],
    hasVideo: true,
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    serviceHistoryPresent: true,
    serviceHistoryStatus: "full",
    serviceRecords: [
      { date: "2023-04-18", mileage: 10200, type: "Full Service", location: "Hyundai Main Dealer, Manchester" },
    ],
    documents: [
      { name: "V5C Logbook", present: true },
      { name: "MOT Certificate", present: true },
      { name: "Service Book", present: true },
      { name: "Spare Key", present: true },
    ],
    conditionItems: [
      {
      id: "c1",
            title: "surface mark on passenger door lower edge",
            severity: "advisory",
            photo: "/images/vehicles/car-10.jpg?v=2",
            photoAlt: "Surface mark on passenger door lower edge",
            detail: "only visible at certain angles, no depth",
          },
    ],
    motHistory: [
      {
        date: "2025-03-14",
        result: "pass",
        mileage: 13800,
        advisories: [],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
    ],
    motExpiry: "2026-03-14",
    runningCosts: { mpgCombined: 55, mpgUrban: 47, mpgExtra: 60, insuranceGroup: 8, roadTaxAnnual: 155, co2gkm: 117 },
    lat: 53.4968, lng: -2.5149,
    isTrade: false,
    listedAt: "2024-11-12T09:00:00Z",
    isSold: true,
  },
  // ─── Trade vehicles ────────────────────────────────────────────────
  {
    id: "t001",
    slug: "2013-ford-focus-zetec-trade",
    make: "Ford",
    model: "Focus",
    variant: "1.6 TDCi Zetec 5dr",
    year: 2013,
    mileage: 119400,
    fuelType: "Diesel",
    transmission: "Manual",
    bodyType: "Hatchback",
    doors: 5,
    seats: 5,
    colour: "Panther Black",
    registration: "MA13 TRD",
    engineCC: 1560,
    price: 2995,
    description: "Trade clearance Focus TDCi — honest runner. Multiple condition items detailed below.",
    images: ["/images/vehicles/car-11.jpg?v=2"],
    hasVideo: false,
    serviceHistoryPresent: false,
    serviceHistoryStatus: "none",
    serviceRecords: [],
    v5cStatus: "applied-for",
    formerKeepers: 6,
    keys: { count: 1, sparePresent: false },
    documentImages: [
      {
        id: "t001-d1",
        type: "mot-certificate",
        label: "MOT certificate",
        imageUrl: "/images/vehicles/car-11.jpg?v=2",
        alt: "MOT certificate",
      },
    ],
    documents: [
      { name: "V5C Logbook", present: true },
      { name: "MOT Certificate", present: true },
      { name: "Service Book", present: false },
      { name: "Spare Key", present: false },
    ],
    conditionItems: [
      {
      id: "c1",
            title: "dents and scratches throughout",
            severity: "minor",
            photo: "/images/vehicles/car-11.jpg?v=2",
            photoAlt: "Dents and scratches throughout",
            detail: "consistent with age",
          },
      {
      id: "c2",
            title: "Nearside rear quarter has a 60mm dent with scuffed paint",
            severity: "major",
            photo: "/images/vehicles/car-11.jpg?v=2",
            photoAlt: "Nearside rear quarter has a 60mm dent with scuffed paint — 60mm",
            qualifiers: ["60mm"],
          },
      {
      id: "c3",
            title: "Driver seat has a significant tear",
            severity: "minor",
            photo: "/images/vehicles/car-11.jpg?v=2",
            photoAlt: "Driver seat has a significant tear — 10cm",
            qualifiers: ["10cm"],
            detail: "approximately 10cm on backrest",
          },
      {
      id: "c4",
            title: "Slight oil consumption",
            severity: "minor",
            photo: "/images/vehicles/car-11.jpg?v=2",
            photoAlt: "Slight oil consumption",
            detail: "approximately 500ml between services. No warning lights.",
          },
    ],
    motHistory: [
      {
        date: "2024-10-08",
        result: "pass",
        mileage: 118200,
        advisories: ["Sill corroded nearside — monitor", "Rear tyre approaching limit"],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
    ],
    motExpiry: "2025-10-08",
    runningCosts: { mpgCombined: 65, mpgUrban: 55, mpgExtra: 70, insuranceGroup: 14, roadTaxAnnual: 155, co2gkm: 115 },
    lat: 53.4968, lng: -2.5149,
    status: "trade",
    isTrade: true,
    listedAt: "2024-10-10T08:00:00Z",
  },
  {
    id: "t002",
    slug: "2012-vauxhall-corsa-sxi-trade",
    make: "Vauxhall",
    model: "Corsa",
    variant: "1.2 i SXi 3dr",
    year: 2012,
    mileage: 94200,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    doors: 3,
    seats: 5,
    colour: "Lightning Blue",
    registration: "BD12 TRD",
    engineCC: 1229,
    price: 1995,
    description: "Trade-priced Corsa. Starts and drives well. Cosmetically tired. Honest runner.",
    images: ["/images/vehicles/car-01.jpg?v=2"],
    hasVideo: false,
    serviceHistoryPresent: false,
    serviceHistoryStatus: "none",
    serviceRecords: [],
    documents: [
      { name: "V5C Logbook", present: true },
      { name: "MOT Certificate", present: true },
      { name: "Service Book", present: false },
      { name: "Spare Key", present: false },
    ],
    conditionItems: [
      {
      id: "c1",
            title: "Faded paint on roof and bonnet",
            severity: "minor",
            photo: "/images/vehicles/car-01.jpg?v=2",
            photoAlt: "Faded paint on roof and bonnet",
            detail: "common for this colour/age",
          },
      {
      id: "c2",
            title: "Front bumper has a crack on nearside corner",
            severity: "minor",
            photo: "/images/vehicles/car-01.jpg?v=2",
            photoAlt: "Front bumper has a crack on nearside corner",
            detail: "secured",
          },
      {
      id: "c3",
            title: "Dash has a crack across the centre",
            severity: "advisory",
            photo: "/images/vehicles/car-01.jpg?v=2",
            photoAlt: "Dash has a crack across the centre",
            detail: "not affecting function",
          },
    ],
    motHistory: [
      {
        date: "2024-11-01",
        result: "pass",
        mileage: 93800,
        advisories: ["Front tyre worn — replace soon"],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
    ],
    motExpiry: "2025-11-01",
    runningCosts: { mpgCombined: 44, mpgUrban: 37, mpgExtra: 49, insuranceGroup: 4, roadTaxAnnual: 155, co2gkm: 145 },
    lat: 53.4968, lng: -2.5149,
    status: "trade",
    isTrade: true,
    listedAt: "2024-11-03T10:00:00Z",
  },
];

export const retailVehicles = getRetailStock(vehicles);
export const tradeVehicles = getTradeStock(vehicles);

export function getVehicleById(id: string): Vehicle | undefined {
  return vehicles.find((v) => v.id === id);
}

export function getRetailVehicleById(id: string): Vehicle | undefined {
  const vehicle = getVehicleById(id);
  return vehicle && isRetailVehicle(vehicle) ? vehicle : undefined;
}

export function getTradeVehicleById(id: string): Vehicle | undefined {
  const vehicle = getVehicleById(id);
  return vehicle && isTradeVehicle(vehicle) ? vehicle : undefined;
}

export function getVehicleBySlug(slug: string): Vehicle | undefined {
  return vehicles.find((v) => v.slug === slug);
}
