import type { Vehicle } from "@/lib/types";

export const vehicles: Vehicle[] = [
  {
    id: "v001",
    slug: "2018-ford-focus-st-line",
    make: "Ford",
    model: "Focus",
    variant: "1.5 EcoBoost ST-Line 5dr",
    year: 2018,
    mileage: 54200,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    doors: 5,
    seats: 5,
    colour: "Magnetic Grey",
    engineCC: 1499,
    price: 8995,
    description:
      "A well-presented Focus ST-Line in Magnetic Grey. Drives solidly with good power delivery. Service history present. A few minor stone chips on the bonnet — all declared.",
    images: ["/images/vehicles/car-06.jpg?v=2"],
    hasVideo: true,
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    serviceHistoryPresent: true,
    serviceRecords: [
      { date: "2019-04-12", mileage: 12300, type: "Interim Service", location: "Ford Main Dealer, Manchester" },
      { date: "2020-04-08", mileage: 24100, type: "Full Service", location: "Ford Main Dealer, Manchester" },
      { date: "2021-05-20", mileage: 36400, type: "Full Service", location: "Kwik Fit, Salford" },
      { date: "2022-06-15", mileage: 46800, type: "Interim Service", location: "Independent, Leigh" },
    ],
    documents: [
      { name: "V5C Logbook", present: true },
      { name: "MOT Certificate", present: true },
      { name: "Service Book", present: true },
      { name: "Spare Key", present: false },
    ],
    conditionItems: [
      { id: "c1", area: "Bodywork", description: "Minor stone chips on bonnet leading edge, approximately 6–8 chips under 3mm", severity: "advisory" },
      { id: "c2", area: "Bodywork", description: "Light surface scratch on rear nearside door, 4cm — does not break the paint", severity: "advisory" },
      { id: "c3", area: "Interior", description: "Driver seat bolster shows normal wear consistent with age and mileage", severity: "advisory" },
      { id: "c4", area: "Tyres", description: "Nearside front tyre at 3mm — legal but recommend replacement within 6 months", severity: "minor", qualifier: "3mm tread depth" },
    ],
    motHistory: [
      {
        date: "2024-03-14",
        result: "pass",
        mileage: 51200,
        advisories: ["Tyre worn close to legal limit (4.1.E.1) — nearside front"],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
      {
        date: "2023-03-09",
        result: "pass",
        mileage: 44100,
        advisories: ["Wiper blade smearing (8.2.4) — driver side"],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
      {
        date: "2022-03-22",
        result: "fail",
        mileage: 36900,
        advisories: [],
        failures: ["Nearside front brake disc worn below minimum thickness (1.1.11 (a) (i))"],
        testCenter: "Kwik Fit, Salford",
      },
      {
        date: "2022-04-04",
        result: "pass",
        mileage: 36910,
        advisories: [],
        failures: [],
        testCenter: "Kwik Fit, Salford",
      },
    ],
    motExpiry: "2025-03-14",
    runningCosts: { mpgCombined: 44, mpgUrban: 37, mpgExtra: 50, insuranceGroup: 18, roadTaxAnnual: 195, co2gkm: 148 },
    formerKeepers: 2,
    lat: 53.4968, lng: -2.5149,
    isTrade: false,
    listedAt: "2024-11-01T10:00:00Z",
  },
  {
    id: "v002",
    slug: "2016-volkswagen-golf-gt",
    make: "Volkswagen",
    model: "Golf",
    variant: "2.0 TDI GT 5dr",
    year: 2016,
    mileage: 78400,
    fuelType: "Diesel",
    transmission: "Manual",
    bodyType: "Hatchback",
    doors: 5,
    seats: 5,
    colour: "Urano Grey",
    engineCC: 1968,
    price: 6995,
    description:
      "Solid Golf GT TDI — great motorway cruiser with good economy. Full service history to 68k then a gap. Two minor rust bubbles on nearside sill declared.",
    images: ["/images/vehicles/car-02.jpg?v=2"],
    hasVideo: false,
    serviceHistoryPresent: true,
    serviceRecords: [
      { date: "2017-05-10", mileage: 18200, type: "Full Service", location: "VW Main Dealer, Bolton" },
      { date: "2018-05-14", mileage: 30100, type: "Full Service", location: "VW Main Dealer, Bolton" },
      { date: "2019-06-20", mileage: 43400, type: "Full Service", location: "VW Main Dealer, Bolton" },
      { date: "2020-07-08", mileage: 55600, type: "Interim Service", location: "Halfords Autocentre" },
      { date: "2021-08-02", mileage: 68000, type: "Full Service", location: "Halfords Autocentre" },
    ],
    documents: [
      { name: "V5C Logbook", present: true },
      { name: "MOT Certificate", present: true },
      { name: "Service Book", present: true },
      { name: "Spare Key", present: true },
    ],
    conditionItems: [
      { id: "c1", area: "Bodywork", description: "Two small rust bubbles on nearside sill — approx 5mm each, have been treated but visible", severity: "minor" },
      { id: "c2", area: "Bodywork", description: "Scuff mark on offside rear bumper, approx 8cm — colour transfer from minor car park contact", severity: "advisory" },
      { id: "c3", area: "Interior", description: "Centre console lid has a crack across the hinge — functional but cosmetically imperfect", severity: "advisory" },
    ],
    motHistory: [
      {
        date: "2024-06-18",
        result: "pass",
        mileage: 76100,
        advisories: ["Nearside sill corroded (7.1.1 (a)) — monitor"],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
      {
        date: "2023-06-12",
        result: "pass",
        mileage: 70200,
        advisories: ["Windscreen wiper blade deteriorated (8.2.4)"],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
    ],
    motExpiry: "2025-06-18",
    runningCosts: { mpgCombined: 61, mpgUrban: 51, mpgExtra: 67, insuranceGroup: 22, roadTaxAnnual: 165, co2gkm: 122 },
    lat: 53.4968, lng: -2.5149,
    isTrade: false,
    listedAt: "2024-10-15T09:30:00Z",
  },
  {
    id: "v003",
    slug: "2020-vauxhall-astra-sri",
    make: "Vauxhall",
    model: "Astra",
    variant: "1.2 Turbo SRi 5dr",
    year: 2020,
    mileage: 31800,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    doors: 5,
    seats: 5,
    colour: "Sovereign Silver",
    engineCC: 1199,
    price: 11495,
    description:
      "Low mileage Astra SRi in very good condition overall. Virtually unmarked interior. Two advisory items declared — both cosmetic.",
    images: ["/images/vehicles/car-09.jpg?v=2"],
    hasVideo: true,
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    serviceHistoryPresent: true,
    serviceRecords: [
      { date: "2021-04-20", mileage: 10200, type: "Full Service", location: "Vauxhall Main Dealer, Wigan" },
      { date: "2022-05-11", mileage: 20800, type: "Full Service", location: "Vauxhall Main Dealer, Wigan" },
      { date: "2023-06-08", mileage: 30100, type: "Interim Service", location: "BBC Autos, Leigh" },
    ],
    documents: [
      { name: "V5C Logbook", present: true },
      { name: "MOT Certificate", present: true },
      { name: "Service Book", present: true },
      { name: "Spare Key", present: true },
    ],
    conditionItems: [
      { id: "c1", area: "Bodywork", description: "Tiny stone chip on roof front edge — 1mm, no rust", severity: "advisory" },
      { id: "c2", area: "Bodywork", description: "Very light swirl marks on bonnet visible in direct sunlight — common with silver paint", severity: "advisory" },
    ],
    motHistory: [
      {
        date: "2024-05-02",
        result: "pass",
        mileage: 30100,
        advisories: [],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
      {
        date: "2023-05-09",
        result: "pass",
        mileage: 21400,
        advisories: [],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
    ],
    motExpiry: "2025-05-02",
    runningCosts: { mpgCombined: 47, mpgUrban: 40, mpgExtra: 52, insuranceGroup: 14, roadTaxAnnual: 180, co2gkm: 135 },
    lat: 53.4968, lng: -2.5149,
    isTrade: false,
    listedAt: "2024-11-10T11:00:00Z",
  },
  {
    id: "v004",
    slug: "2015-honda-jazz-se",
    make: "Honda",
    model: "Jazz",
    variant: "1.3 i-VTEC SE 5dr",
    year: 2015,
    mileage: 62100,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    doors: 5,
    seats: 5,
    colour: "Crystal Black",
    engineCC: 1339,
    price: 5995,
    description:
      "Reliable Jazz SE with very practical Magic Seats. Well maintained with consistent service history. A few age-related marks — all declared.",
    images: ["/images/vehicles/car-04.jpg?v=2"],
    hasVideo: false,
    serviceHistoryPresent: true,
    serviceRecords: [
      { date: "2016-06-14", mileage: 11200, type: "Full Service", location: "Honda Main Dealer, Warrington" },
      { date: "2017-07-03", mileage: 22400, type: "Full Service", location: "Honda Main Dealer, Warrington" },
      { date: "2018-07-22", mileage: 33600, type: "Full Service", location: "Honda Main Dealer, Warrington" },
      { date: "2019-08-15", mileage: 43200, type: "Interim Service", location: "Independent, Leigh" },
      { date: "2021-09-10", mileage: 56800, type: "Full Service", location: "Independent, Leigh" },
    ],
    documents: [
      { name: "V5C Logbook", present: true },
      { name: "MOT Certificate", present: true },
      { name: "Service Book", present: true },
      { name: "Spare Key", present: false },
    ],
    conditionItems: [
      { id: "c1", area: "Bodywork", description: "Chips and light scratches on rear bumper — typical for age", severity: "advisory" },
      { id: "c2", area: "Interior", description: "Rear seat squab has a small (2cm) tear on the passenger side — not visible when folded", severity: "advisory" },
      { id: "c3", area: "Bodywork", description: "Small dent on offside rear quarter — 20mm, no paint damage", severity: "minor" },
    ],
    motHistory: [
      {
        date: "2024-08-20",
        result: "pass",
        mileage: 60400,
        advisories: ["Rear brake pads approaching minimum (1.2.1 (f) (i))"],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
      {
        date: "2023-08-14",
        result: "pass",
        mileage: 56100,
        advisories: [],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
    ],
    motExpiry: "2025-08-20",
    runningCosts: { mpgCombined: 54, mpgUrban: 46, mpgExtra: 59, insuranceGroup: 9, roadTaxAnnual: 155, co2gkm: 119 },
    lat: 53.4968, lng: -2.5149,
    isTrade: false,
    listedAt: "2024-09-20T14:00:00Z",
  },
  {
    id: "v005",
    slug: "2019-toyota-yaris-icon-tech",
    make: "Toyota",
    model: "Yaris",
    variant: "1.5 VVT-i Icon Tech 5dr",
    year: 2019,
    mileage: 28400,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    doors: 5,
    seats: 5,
    colour: "Chilli Red",
    engineCC: 1496,
    price: 10995,
    description:
      "Excellent low mileage Yaris in Chilli Red. Known for reliability. One advisory item on the last MOT — noted here for transparency.",
    images: ["/images/vehicles/car-05.jpg?v=2"],
    hasVideo: true,
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    serviceHistoryPresent: true,
    serviceRecords: [
      { date: "2020-05-08", mileage: 10100, type: "Full Service", location: "Toyota Main Dealer, Manchester" },
      { date: "2021-05-14", mileage: 17800, type: "Full Service", location: "Toyota Main Dealer, Manchester" },
      { date: "2022-06-01", mileage: 23200, type: "Interim Service", location: "Toyota Main Dealer, Manchester" },
    ],
    documents: [
      { name: "V5C Logbook", present: true },
      { name: "MOT Certificate", present: true },
      { name: "Service Book", present: true },
      { name: "Spare Key", present: true },
    ],
    conditionItems: [
      { id: "c1", area: "Bodywork", description: "Minor chip on offside front door lower edge — 2mm, no rust present", severity: "advisory" },
    ],
    motHistory: [
      {
        date: "2024-04-22",
        result: "pass",
        mileage: 27100,
        advisories: ["Bonnet release mechanism slightly stiff (3.4.1 (a)) — lubricated at test"],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
      {
        date: "2023-04-18",
        result: "pass",
        mileage: 22400,
        advisories: [],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
    ],
    motExpiry: "2025-04-22",
    runningCosts: { mpgCombined: 51, mpgUrban: 44, mpgExtra: 56, insuranceGroup: 10, roadTaxAnnual: 170, co2gkm: 126 },
    lat: 53.4968, lng: -2.5149,
    isTrade: false,
    listedAt: "2024-10-28T09:00:00Z",
  },
  {
    id: "v006",
    slug: "2014-bmw-3-series-320d",
    make: "BMW",
    model: "3 Series",
    variant: "320d SE Saloon",
    year: 2014,
    mileage: 102300,
    fuelType: "Diesel",
    transmission: "Manual",
    bodyType: "Saloon",
    doors: 4,
    seats: 5,
    colour: "Space Grey",
    engineCC: 1995,
    price: 7995,
    description:
      "High mileage but well maintained 320d — these engines are known to last 200k+ with care. Full service history to 98k. Multiple condition items declared.",
    images: ["/images/vehicles/car-06.jpg?v=2"],
    hasVideo: true,
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    serviceHistoryPresent: true,
    serviceRecords: [
      { date: "2015-09-10", mileage: 18400, type: "Full Service", location: "BMW Main Dealer, Manchester" },
      { date: "2016-09-12", mileage: 34600, type: "Full Service", location: "BMW Main Dealer, Manchester" },
      { date: "2017-09-18", mileage: 50200, type: "Full Service", location: "BMW Main Dealer, Manchester" },
      { date: "2018-10-04", mileage: 65800, type: "Full Service", location: "Independent BMW Specialist" },
      { date: "2019-10-14", mileage: 79400, type: "Full Service", location: "Independent BMW Specialist" },
      { date: "2020-11-02", mileage: 90100, type: "Full Service", location: "Independent BMW Specialist" },
      { date: "2022-01-24", mileage: 98200, type: "Interim Service", location: "Independent BMW Specialist" },
    ],
    documents: [
      { name: "V5C Logbook", present: true },
      { name: "MOT Certificate", present: true },
      { name: "Service Book", present: true },
      { name: "Spare Key", present: true },
    ],
    conditionItems: [
      { id: "c1", area: "Bodywork", description: "Scratch on nearside front wing — 15cm, faded paint visible", severity: "minor" },
      { id: "c2", area: "Bodywork", description: "Light surface corrosion on both sills — cosmetic at present, not structural", severity: "minor" },
      { id: "c3", area: "Interior", description: "Driver armrest has a 3cm split in the leather — common on this model at this age", severity: "advisory" },
      { id: "c4", area: "Interior", description: "iDrive controller knob has wear marks — functional", severity: "advisory" },
      { id: "c5", area: "Tyres", description: "Both rear tyres at 3mm — legal, recommend replacement soon", severity: "minor" },
      { id: "c6", area: "Engine", description: "Minor oil seep from rocker cover gasket — drip-free at present, monitor", severity: "advisory" },
    ],
    motHistory: [
      {
        date: "2024-07-10",
        result: "pass",
        mileage: 99800,
        advisories: ["Sill corrosion nearside — monitor (7.1.1 (a))", "Rear tyre worn (4.1.E.1)"],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
      {
        date: "2023-07-06",
        result: "fail",
        mileage: 94200,
        advisories: [],
        failures: ["Offside headlamp aim too low (4.3.1 (b) (i))"],
        testCenter: "BBC Autos, Leigh",
      },
      {
        date: "2023-07-06",
        result: "pass",
        mileage: 94200,
        advisories: [],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
    ],
    motExpiry: "2025-07-10",
    runningCosts: { mpgCombined: 57, mpgUrban: 47, mpgExtra: 64, insuranceGroup: 28, roadTaxAnnual: 165, co2gkm: 129 },
    lat: 53.4968, lng: -2.5149,
    isTrade: false,
    listedAt: "2024-09-05T08:30:00Z",
  },
  {
    id: "v007",
    slug: "2021-kia-picanto-2",
    make: "Kia",
    model: "Picanto",
    variant: "1.0 2 5dr",
    year: 2021,
    mileage: 18600,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    doors: 5,
    seats: 5,
    colour: "Infra Red",
    engineCC: 998,
    price: 9495,
    description:
      "Practically new low mileage Picanto. The ideal first or city car. Virtually unmarked — only one advisory item noted.",
    images: ["/images/vehicles/car-07.jpg?v=2"],
    hasVideo: false,
    serviceHistoryPresent: true,
    serviceRecords: [
      { date: "2022-06-14", mileage: 8200, type: "Full Service", location: "Kia Main Dealer, Bolton" },
    ],
    documents: [
      { name: "V5C Logbook", present: true },
      { name: "MOT Certificate", present: true },
      { name: "Service Book", present: true },
      { name: "Spare Key", present: true },
    ],
    conditionItems: [
      { id: "c1", area: "Bodywork", description: "Very faint mark on front bumper centre — barely visible, no depth", severity: "advisory" },
    ],
    motHistory: [
      {
        date: "2024-06-10",
        result: "pass",
        mileage: 17800,
        advisories: [],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
    ],
    motExpiry: "2025-06-10",
    runningCosts: { mpgCombined: 56, mpgUrban: 48, mpgExtra: 61, insuranceGroup: 6, roadTaxAnnual: 155, co2gkm: 114 },
    lat: 53.4968, lng: -2.5149,
    isTrade: false,
    listedAt: "2024-11-05T12:00:00Z",
  },
  {
    id: "v008",
    slug: "2017-ford-transit-custom",
    make: "Ford",
    model: "Transit Custom",
    variant: "2.0 TDCi 290 L1 H1 Limited",
    year: 2017,
    mileage: 88700,
    fuelType: "Diesel",
    transmission: "Manual",
    bodyType: "Van",
    doors: 3,
    seats: 3,
    colour: "Frozen White",
    engineCC: 1995,
    price: 10995,
    description:
      "Well specified Transit Custom Limited in Frozen White. Multiple condition items declared openly — primarily cosmetic with one mechanical item.",
    images: ["/images/vehicles/car-08.jpg?v=2"],
    hasVideo: true,
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    serviceHistoryPresent: true,
    serviceRecords: [
      { date: "2018-07-20", mileage: 22400, type: "Full Service", location: "Ford Main Dealer, Manchester" },
      { date: "2019-07-18", mileage: 44800, type: "Full Service", location: "Ford Main Dealer, Manchester" },
      { date: "2020-08-12", mileage: 62100, type: "Interim Service", location: "Kwik Fit" },
      { date: "2021-09-03", mileage: 76400, type: "Full Service", location: "Independent" },
    ],
    documents: [
      { name: "V5C Logbook", present: true },
      { name: "MOT Certificate", present: true },
      { name: "Service Book", present: false },
      { name: "Spare Key", present: false },
    ],
    conditionItems: [
      { id: "c1", area: "Bodywork", description: "Multiple scratches and dents on rear doors consistent with commercial use — all cosmetic", severity: "minor" },
      { id: "c2", area: "Bodywork", description: "Offside front wing has a 30mm dent — shallow, paint intact", severity: "minor" },
      { id: "c3", area: "Interior", description: "Cab carpet worn through — typical work van use", severity: "advisory" },
      { id: "c4", area: "Engine", description: "EGR valve has been cleaned but may require replacement within 12–18 months based on mileage", severity: "minor" },
    ],
    motHistory: [
      {
        date: "2024-09-04",
        result: "pass",
        mileage: 86200,
        advisories: ["Windscreen chip in driver's critical zone (8.1.2 (a) (ii)) — repaired prior to test"],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
      {
        date: "2023-09-11",
        result: "fail",
        mileage: 79400,
        advisories: [],
        failures: ["Offside front brake disc worn (1.1.11 (a) (i))", "Nearside wiper blade not clearing (8.2.4)"],
        testCenter: "BBC Autos, Leigh",
      },
      {
        date: "2023-09-20",
        result: "pass",
        mileage: 79410,
        advisories: [],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
    ],
    motExpiry: "2025-09-04",
    runningCosts: { mpgCombined: 34, mpgUrban: 28, mpgExtra: 38, insuranceGroup: 36, roadTaxAnnual: 290, co2gkm: 218 },
    lat: 53.4968, lng: -2.5149,
    isTrade: false,
    listedAt: "2024-10-01T10:30:00Z",
  },
  {
    id: "v009",
    slug: "2017-nissan-qashqai-acenta",
    make: "Nissan",
    model: "Qashqai",
    variant: "1.2 DiG-T Acenta 5dr",
    year: 2017,
    mileage: 49800,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "SUV",
    doors: 5,
    seats: 5,
    colour: "Blade Silver",
    engineCC: 1197,
    price: 8495,
    description:
      "Popular Qashqai Acenta in very presentable condition. Low faults — just one advisory chip on the bonnet. Good service history.",
    images: ["/images/vehicles/car-09.jpg?v=2"],
    hasVideo: false,
    serviceHistoryPresent: true,
    serviceRecords: [
      { date: "2018-06-22", mileage: 12800, type: "Full Service", location: "Nissan Main Dealer, Wigan" },
      { date: "2019-06-14", mileage: 24200, type: "Full Service", location: "Nissan Main Dealer, Wigan" },
      { date: "2020-07-18", mileage: 34800, type: "Interim Service", location: "Halfords Autocentre" },
      { date: "2021-08-09", mileage: 43600, type: "Full Service", location: "Independent" },
    ],
    documents: [
      { name: "V5C Logbook", present: true },
      { name: "MOT Certificate", present: true },
      { name: "Service Book", present: true },
      { name: "Spare Key", present: false },
    ],
    conditionItems: [
      { id: "c1", area: "Bodywork", description: "Two stone chips on bonnet — 2mm and 3mm, no rust", severity: "advisory" },
    ],
    motHistory: [
      {
        date: "2024-06-28",
        result: "pass",
        mileage: 47200,
        advisories: [],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
      {
        date: "2023-06-30",
        result: "pass",
        mileage: 43100,
        advisories: ["Nearside rear wiper blade smearing (8.2.4)"],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
    ],
    motExpiry: "2025-06-28",
    runningCosts: { mpgCombined: 43, mpgUrban: 36, mpgExtra: 48, insuranceGroup: 15, roadTaxAnnual: 180, co2gkm: 149 },
    lat: 53.4968, lng: -2.5149,
    isTrade: false,
    listedAt: "2024-10-20T11:00:00Z",
  },
  {
    id: "v010",
    slug: "2022-hyundai-i20-se-connect",
    make: "Hyundai",
    model: "i20",
    variant: "1.0 T-GDi SE Connect 5dr",
    year: 2022,
    mileage: 14200,
    fuelType: "Mild Hybrid",
    transmission: "Manual",
    bodyType: "Hatchback",
    doors: 5,
    seats: 5,
    colour: "Atlas White",
    engineCC: 998,
    price: 13495,
    description:
      "Nearly new i20 in Atlas White — virtually unmarked with low mileage. Mild hybrid tech for better economy. Full manufacturer history.",
    images: ["/images/vehicles/car-10.jpg?v=2"],
    hasVideo: true,
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    serviceHistoryPresent: true,
    serviceRecords: [
      { date: "2023-04-18", mileage: 10200, type: "Full Service", location: "Hyundai Main Dealer, Manchester" },
    ],
    documents: [
      { name: "V5C Logbook", present: true },
      { name: "MOT Certificate", present: true },
      { name: "Service Book", present: true },
      { name: "Spare Key", present: true },
    ],
    conditionItems: [
      { id: "c1", area: "Bodywork", description: "Extremely faint surface mark on passenger door lower edge — only visible at certain angles, no depth", severity: "advisory" },
    ],
    motHistory: [
      {
        date: "2025-03-14",
        result: "pass",
        mileage: 13800,
        advisories: [],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
    ],
    motExpiry: "2026-03-14",
    runningCosts: { mpgCombined: 55, mpgUrban: 47, mpgExtra: 60, insuranceGroup: 8, roadTaxAnnual: 155, co2gkm: 117 },
    lat: 53.4968, lng: -2.5149,
    isTrade: false,
    listedAt: "2024-11-12T09:00:00Z",
  },
  // ─── Trade vehicles ────────────────────────────────────────────────
  {
    id: "t001",
    slug: "2013-ford-focus-zetec-trade",
    make: "Ford",
    model: "Focus",
    variant: "1.6 TDCi Zetec 5dr",
    year: 2013,
    mileage: 119400,
    fuelType: "Diesel",
    transmission: "Manual",
    bodyType: "Hatchback",
    doors: 5,
    seats: 5,
    colour: "Panther Black",
    registration: "MA13 TRD",
    engineCC: 1560,
    price: 2995,
    description: "Trade clearance Focus TDCi — honest runner. Multiple condition items detailed below.",
    images: ["/images/vehicles/car-11.jpg?v=2"],
    hasVideo: false,
    serviceHistoryPresent: false,
    serviceRecords: [],
    documents: [
      { name: "V5C Logbook", present: true },
      { name: "MOT Certificate", present: true },
      { name: "Service Book", present: false },
      { name: "Spare Key", present: false },
    ],
    conditionItems: [
      { id: "c1", area: "Bodywork", description: "Multiple minor dents and scratches throughout — consistent with age", severity: "minor" },
      { id: "c2", area: "Bodywork", description: "Nearside rear quarter has a 60mm dent with scuffed paint", severity: "major" },
      { id: "c3", area: "Interior", description: "Driver seat has a significant tear — approximately 10cm on backrest", severity: "minor" },
      { id: "c4", area: "Engine", description: "Slight oil consumption — approximately 500ml between services. No warning lights.", severity: "minor" },
    ],
    motHistory: [
      {
        date: "2024-10-08",
        result: "pass",
        mileage: 118200,
        advisories: ["Sill corroded nearside — monitor", "Rear tyre approaching limit"],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
    ],
    motExpiry: "2025-10-08",
    runningCosts: { mpgCombined: 65, mpgUrban: 55, mpgExtra: 70, insuranceGroup: 14, roadTaxAnnual: 155, co2gkm: 115 },
    lat: 53.4968, lng: -2.5149,
    isTrade: true,
    listedAt: "2024-10-10T08:00:00Z",
  },
  {
    id: "t002",
    slug: "2012-vauxhall-corsa-sxi-trade",
    make: "Vauxhall",
    model: "Corsa",
    variant: "1.2 i SXi 3dr",
    year: 2012,
    mileage: 94200,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    doors: 3,
    seats: 5,
    colour: "Lightning Blue",
    registration: "BD12 TRD",
    engineCC: 1229,
    price: 1995,
    description: "Trade-priced Corsa. Starts and drives well. Cosmetically tired. Honest runner.",
    images: ["/images/vehicles/car-01.jpg?v=2"],
    hasVideo: false,
    serviceHistoryPresent: false,
    serviceRecords: [],
    documents: [
      { name: "V5C Logbook", present: true },
      { name: "MOT Certificate", present: true },
      { name: "Service Book", present: false },
      { name: "Spare Key", present: false },
    ],
    conditionItems: [
      { id: "c1", area: "Bodywork", description: "Faded paint on roof and bonnet — common for this colour/age", severity: "minor" },
      { id: "c2", area: "Bodywork", description: "Front bumper has a crack on nearside corner — secured", severity: "minor" },
      { id: "c3", area: "Interior", description: "Dash has a crack across the centre — not affecting function", severity: "advisory" },
    ],
    motHistory: [
      {
        date: "2024-11-01",
        result: "pass",
        mileage: 93800,
        advisories: ["Front tyre worn — replace soon"],
        failures: [],
        testCenter: "BBC Autos, Leigh",
      },
    ],
    motExpiry: "2025-11-01",
    runningCosts: { mpgCombined: 44, mpgUrban: 37, mpgExtra: 49, insuranceGroup: 4, roadTaxAnnual: 155, co2gkm: 145 },
    lat: 53.4968, lng: -2.5149,
    isTrade: true,
    listedAt: "2024-11-03T10:00:00Z",
  },
];

export const retailVehicles = vehicles.filter((v) => !v.isTrade);
export const tradeVehicles = vehicles.filter((v) => v.isTrade);

export function getVehicleById(id: string): Vehicle | undefined {
  return vehicles.find((v) => v.id === id);
}

export function getRetailVehicleById(id: string): Vehicle | undefined {
  const vehicle = getVehicleById(id);
  return vehicle && !vehicle.isTrade ? vehicle : undefined;
}

export function getTradeVehicleById(id: string): Vehicle | undefined {
  const vehicle = getVehicleById(id);
  return vehicle?.isTrade ? vehicle : undefined;
}

export function getVehicleBySlug(slug: string): Vehicle | undefined {
  return vehicles.find((v) => v.slug === slug);
}
